image: "node:5.6.0"

stages:
  - test
  - deploy

before_script:
  - CACHE_DIR=${CI_PROJECT_DIR}/${CI_BUILD_REF_NAME}/cache
  - mkdir -p CACHE_DIR
  - ln -s $PWD/node_modules CACHE_DIR
  - npm install --production

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm run deploy
