image: "node:5.6.0"

stages:
  - install
  - test

install:
  stage: install
  script:
    - mkdir node_modules && touch node_modules/WORKS.md
    - export CACHE_DIR=${CI_PROJECT_DIR}/${CI_BUILD_REF_NAME}/cache/node_modules
    - mkdir -p $CACHE_DIR
    - ln -s $PWD/node_modules $CACHE_DIR

test:
  stage: test
  script:
    - ls $PWD/node_modules
