image: "node:5.6.0"

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/
  group: dependencycache

before_script:
  - npm install --production

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm run deploy
