image: "node:5.6.0"

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - npm install --production
    - export CACHE_DIR=${CI_PROJECT_DIR}/${CI_BUILD_REF_NAME}/cache/node_modules
    - mkdir -p $CACHE_DIR
    - ln -s $PWD/node_modules $CACHE_DIR

test:
  stage: test
  script:
    - ln -s $CACHE_DIR $PWD/node_modules
    - ls $PWD/node_modules

deploy:
  stage: deploy
  script:
    - ln -s $CACHE_DIR $PWD/node_modules
    - npm run deploy
