image: "node:5.6.0"

stages:
  - install
  - test
  - deploy

cache:
  paths:
    - node_modules/
  group: sharedcache

install:
  stage: install
  script:
    - npm install --production

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npm run deploy
